// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UtilsInterface is an autogenerated mock type for the UtilsInterface type
type UtilsInterface struct {
	mock.Mock
}

// PlatformDecryptText provides a mock function with given fields: myString
func (_m *UtilsInterface) PlatformDecryptText(myString string) (string, error) {
	ret := _m.Called(myString)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(myString)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(myString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlatformEncryptText provides a mock function with given fields: myString
func (_m *UtilsInterface) PlatformEncryptText(myString string) (string, error) {
	ret := _m.Called(myString)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(myString)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(myString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
