// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "los-kmb-api/models/entity"

	mock "github.com/stretchr/testify/mock"

	request "los-kmb-api/models/request"

	response "los-kmb-api/models/response"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// BlacklistCheck provides a mock function with given fields: index, spDupcheck
func (_m *Usecase) BlacklistCheck(index int, spDupcheck response.SpDupCekCustomerByID) (response.UsecaseApi, string) {
	ret := _m.Called(index, spDupcheck)

	var r0 response.UsecaseApi
	if rf, ok := ret.Get(0).(func(int, response.SpDupCekCustomerByID) response.UsecaseApi); ok {
		r0 = rf(index, spDupcheck)
	} else {
		r0 = ret.Get(0).(response.UsecaseApi)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(int, response.SpDupCekCustomerByID) string); ok {
		r1 = rf(index, spDupcheck)
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// DupcheckIntegrator provides a mock function with given fields: ctx, prospectID, idNumber, legalName, birthDate, surgateName, accessToken
func (_m *Usecase) DupcheckIntegrator(ctx context.Context, prospectID string, idNumber string, legalName string, birthDate string, surgateName string, accessToken string) (response.SpDupCekCustomerByID, error) {
	ret := _m.Called(ctx, prospectID, idNumber, legalName, birthDate, surgateName, accessToken)

	var r0 response.SpDupCekCustomerByID
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) response.SpDupCekCustomerByID); ok {
		r0 = rf(ctx, prospectID, idNumber, legalName, birthDate, surgateName, accessToken)
	} else {
		r0 = ret.Get(0).(response.SpDupCekCustomerByID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, prospectID, idNumber, legalName, birthDate, surgateName, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilteringPefindo provides a mock function with given fields: ctx, reqPefindo, customerStatus, accessToken
func (_m *Usecase) FilteringPefindo(ctx context.Context, reqPefindo request.Pefindo, customerStatus string, accessToken string) (response.Filtering, response.PefindoResult, []entity.TrxDetailBiro, error) {
	ret := _m.Called(ctx, reqPefindo, customerStatus, accessToken)

	var r0 response.Filtering
	if rf, ok := ret.Get(0).(func(context.Context, request.Pefindo, string, string) response.Filtering); ok {
		r0 = rf(ctx, reqPefindo, customerStatus, accessToken)
	} else {
		r0 = ret.Get(0).(response.Filtering)
	}

	var r1 response.PefindoResult
	if rf, ok := ret.Get(1).(func(context.Context, request.Pefindo, string, string) response.PefindoResult); ok {
		r1 = rf(ctx, reqPefindo, customerStatus, accessToken)
	} else {
		r1 = ret.Get(1).(response.PefindoResult)
	}

	var r2 []entity.TrxDetailBiro
	if rf, ok := ret.Get(2).(func(context.Context, request.Pefindo, string, string) []entity.TrxDetailBiro); ok {
		r2 = rf(ctx, reqPefindo, customerStatus, accessToken)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]entity.TrxDetailBiro)
		}
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(context.Context, request.Pefindo, string, string) error); ok {
		r3 = rf(ctx, reqPefindo, customerStatus, accessToken)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// FilteringProspectID provides a mock function with given fields: prospectID
func (_m *Usecase) FilteringProspectID(prospectID string) (request.OrderIDCheck, error) {
	ret := _m.Called(prospectID)

	var r0 request.OrderIDCheck
	if rf, ok := ret.Get(0).(func(string) request.OrderIDCheck); ok {
		r0 = rf(prospectID)
	} else {
		r0 = ret.Get(0).(request.OrderIDCheck)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prospectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResultFiltering provides a mock function with given fields: prospectID
func (_m *Usecase) GetResultFiltering(prospectID string) (response.Filtering, error) {
	ret := _m.Called(prospectID)

	var r0 response.Filtering
	if rf, ok := ret.Get(0).(func(string) response.Filtering); ok {
		r0 = rf(prospectID)
	} else {
		r0 = ret.Get(0).(response.Filtering)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prospectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveFiltering provides a mock function with given fields: transaction, trxDetailBiro
func (_m *Usecase) SaveFiltering(transaction entity.FilteringKMB, trxDetailBiro []entity.TrxDetailBiro) error {
	ret := _m.Called(transaction, trxDetailBiro)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.FilteringKMB, []entity.TrxDetailBiro) error); ok {
		r0 = rf(transaction, trxDetailBiro)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
