package constant

var LOS_KMB_BASE_URL string
var TOPIC_SUBMISSION string
var TOPIC_SUBMISSION_LOS string

const (
	FLAG_LOS                         = "LOS"
	KMB_RESOURCE_ID                  = "los-kmb-api"
	LOBID_KMB                        = 2
	TAG_MAX                          = "max"
	TAG_GT                           = "gt"
	TAG_REQUIRED                     = "required"
	TAG_DATE_FORMAT                  = "dateformat"
	TAG_LEN                          = "len"
	TAG_URL                          = "url"
	TAG_ALLOW_CHARS_NAME             = "allowcharsname"
	TAG_MIN                          = "min"
	TAG_NUMBER                       = "number"
	TAG_ID_NUMBER                    = "id_number"
	TAG_BRANCH_ID                    = "branch_id"
	TAG_ALLOW_NAME                   = "allow_name"
	TAG_GENDER                       = "gender"
	TAG_SPOUSE_GENDER                = "spouse_gender"
	TAG_STATUS_KONSUMEN              = "status_konsumen"
	TAG_RECOM                        = "recom"
	TAG_CHANNEL                      = "channel"
	TAG_LOB                          = "lob"
	TAG_INCOMING                     = "incoming"
	TAG_HOME                         = "home"
	TAG_KTP                          = "ktp"
	TAG_ADDRESS                      = "address"
	TAG_MARITAL                      = "marital"
	TAG_EDUCATION                    = "education"
	TAG_PROFESSION                   = "profession"
	TAG_PHOTO                        = "photo"
	TAG_RELATIONSHIP                 = "relationship"
	TAG_PROSPECTID                   = "prospect_id"
	TAG_FTR_PROSPECTID               = "prospectID"
	TAG_TENOR                        = "tenor"
	TAG_SPOUSE_NULL                  = "mustnull"
	TAG_SPOUSE_NOT_NULL              = "notnull"
	TAG_RELATION                     = "relation"
	TAG_BPKB_NAME                    = "bpkbname"
	ACTIVITY_UNPROCESS               = "UNPR"
	PRESCREENING                     = "PSI"
	ACTIVITY_STOP                    = "STOP"
	ACTIVITY_PROCESS                 = "PRCD"
	STATUS_FINAL                     = "FIN"
	STATUS_ONPROCESS                 = "ONP"
	DECISION_CREDIT_PROCESS          = "CREDIT_PROCESS"
	DB_DECISION_PASS                 = "PAS"
	DB_DECISION_APR                  = "APR"
	DB_DECISION_REJECT               = "REJ"
	DB_DECISION_CANCEL               = "CAN"
	DB_DECISION_CREDIT_PROCESS       = "CPR"
	DB_DECISION_CREDIT_ANALYST       = "CRA"
	DB_DECISION_BRANCH_MANAGER       = "CBM"
	JSON_DECISION_PASS               = "PASS"
	JSON_DECISION_REJECT             = "REJECTED"
	JSON_DECISION_CREDIT_PROCESS     = "CREDIT_PROCESS"
	RECORD_NOT_FOUND                 = "record not found"
	NEW                              = "NEW"
	METHOD_POST                      = "POST"
	METHOD_PUT                       = "PUT"
	METHOD_GET                       = "GET"
	METHOD_DELETE                    = "DELETE"
	CONNECTION_ERROR                 = "ERROR"
	MESSAGE_KMB_FILTERING            = "KMB-FILTERING"
	TIMEOUT                          = 30
	TIME_FORMAT                      = "2006-01-02"
	MARRIED                          = "M"
	BADTYPE_B                        = "B"
	MAX_OVER_DUE_DAYS                = 90
	NUM_OF_ASSET_INVENTORIED         = 0
	BADTYPE_W                        = "W"
	PROFESSION_ID_WRST               = "WRST"
	PROFESSION_ID_PRO                = "PRO"
	IS_SIMILIAR                      = 1
	IS_RESTRUCTURE                   = 1
	CODE_E                           = 701
	MESSAGE_E                        = "ERROR"
	MESSAGE_SUCCESS                  = "SUCCESS"
	PEFINDO_UNSCORE                  = "UNSCORE"
	RESPONSE_PEFINDO_DUMMY_NOT_FOUND = "Pefindo Dummy Data Not Found"
	ERRORS_E                         = "Failed Process Blacklist Confins"
	REASON_E                         = "Failed Process Blacklist Confins"
	SYSTEM_CREATED                   = "SYSTEM"

	CMO_AGENT                  = "CMO"
	CODE_CMO_RECOMMENDED       = "1410"
	REASON_CMO_RECOMMENDED     = "CMO / CO Recommended"
	CMO_NOT_RECOMMEDED         = "0"
	CODE_CMO_NOT_RECOMMEDED    = "1411"
	REASON_CMO_NOT_RECOMMENDED = "CMO / CO Not Recommended"

	NAMA_SAMA                                                    = "nama_sama"
	NAMA_BEDA                                                    = "nama_beda"
	PBK_OVD_LAST_12                                              = 60
	BAKI_DEBET                                                   = 20000000
	PBK_OVD_CURRENT                                              = 30
	USER_PBK_KMB_FILTEERING                                      = "kmbfiltering"
	CODE_SPOSE_BADTYPE_B                                         = "705"
	CODE_SPOSE_MAX_OVER_DUE_DAYS                                 = "7051"
	CODE_SPOSE_NUM_OF_ASSET_INVENTORIED                          = "7052"
	CODE_SPOSE_BADTYPE_W                                         = "7053"
	CODE_SPOSE_BERSIH                                            = "7054"
	CODE_SPOSE_IS_RESTRUCTURE                                    = "7050"
	CODE_IS_RESTRUCTURE                                          = "699"
	CODE_IS_RESTRUCTURE_SPOSE_BADTYPE_B                          = "1301"
	CODE_IS_RESTRUCTURE_SPOSE_MAX_OVER_DUE_DAYS                  = "1302"
	CODE_IS_RESTRUCTURE_SPOSE_NUM_OF_ASSET_INVENTORIED           = "1303"
	CODE_IS_RESTRUCTURE_SPOSE_BADTYPE_W                          = "1304"
	CODE_IS_RESTRUCTURE_SPOSE_BERSIH                             = "1305"
	CODE_NEW_CUSTOMER_SPOSE_IS_RESTRUCTURE                       = "1307"
	CODE_NEW_CUSTOMER_IS_RESTRUCTURE                             = "7017"
	CODE_BADTYPE_B                                               = "702"
	CODE_BADTYPE_B_SPOSE_BADTYPE_B                               = "7021"
	CODE_BADTYPE_B_SPOSE_MAX_OVER_DUE_DAYS                       = "7022"
	CODE_BADTYPE_B_SPOSE_NUM_OF_ASSET_INVENTORIED                = "7023"
	CODE_BADTYPE_B_SPOSE_BADTYPE_W                               = "7024"
	CODE_BADTYPE_B_SPOSE_BERSIH                                  = "7025"
	CODE_BADTYPE_B_SPOSE                                         = "7026"
	CODE_MAX_OVER_DUE_DAYS                                       = "703"
	CODE_MAX_OVER_DUE_DAYS_SPOSE_BADTYPE_B                       = "7031"
	CODE_MAX_OVER_DUE_DAYS_SPOSE_MAX_OVER_DUE_DAYS               = "7032"
	CODE_MAX_OVER_DUE_DAYS_SPOSE_NUM_OF_ASSET_INVENTORIED        = "7033"
	CODE_MAX_OVER_DUE_DAYS_SPOSE_IS_RESTRUCTURE                  = "7034"
	CODE_MAX_OVER_DUE_DAYS_SPOSE_BERSIH                          = "7035"
	CODE_MAX_OVER_DUE_DAYS_SPOSE                                 = "7036"
	CODE_NUM_OF_ASSET_INVENTORIED                                = "704"
	CODE_NUM_OF_ASSET_INVENTORIED_SPOSE_BADTYPE_B                = "7041"
	CODE_NUM_OF_ASSET_INVENTORIED_SPOSE_MAX_OVER_DUE_DAYS        = "7042"
	CODE_NUM_OF_ASSET_INVENTORIED_SPOSE_NUM_OF_ASSET_INVENTORIED = "7043"
	CODE_NUM_OF_ASSET_INVENTORIED_SPOSE_BADTYPE_W                = "7044"
	CODE_NUM_OF_ASSET_INVENTORIED_SPOSE_BERSIH                   = "7045"
	CODE_NUM_OF_ASSET_INVENTORIED_SPOSE                          = "7046"
	CODE_BADTYPE_W                                               = "706"
	CODE_BADTYPE_W_SPOSE_BADTYPE_B                               = "7061"
	CODE_BADTYPE_W_SPOSE_MAX_OVER_DUE_DAYS                       = "7062"
	CODE_BADTYPE_W_SPOSE_NUM_OF_ASSET_INVENTORIED                = "7063"
	CODE_BADTYPE_W_SPOSE_BADTYPE_W                               = "7064"
	CODE_BADTYPE_W_SPOSE_BERSIH                                  = "7065"
	CODE_BADTYPE_W_SPOSE                                         = "7066"
	CODE_IS_SIMILIAR_ID                                          = "707"
	CODE_IS_SIMILIAR_ID_SPOSE_BADTYPE_B                          = "7071"
	CODE_IS_SIMILIAR_ID_SPOSE_MAX_OVER_DUE_DAYS                  = "7072"
	CODE_IS_SIMILIAR_ID_SPOSE_NUM_OF_ASSET_INVENTORIED           = "7073"
	CODE_IS_SIMILIAR_ID_SPOSE_BADTYPE_W                          = "7074"
	CODE_IS_SIMILIAR_ID_SPOSE_BERSIH                             = "7075"
	CODE_IS_SIMILIAR_ID_SPOSE                                    = "7076"
	CODE_BERSIH                                                  = "708"
	CODE_BERSIH_SPOSE_BADTYPE_B                                  = "7091"
	CODE_BERSIH_SPOSE_MAX_OVER_DUE_DAYS                          = "7092"
	CODE_BERSIH_SPOSE_NUM_OF_ASSET_INVENTORIED                   = "7093"
	CODE_BERSIH_SPOSE_BADTYPE_W                                  = "7094"
	CODE_BERSIH_SPOSE_BERSIH                                     = "7095"
	CODE_BERSIH_SPOSE                                            = "7096"
	CODE_NEW_CUSTOMER                                            = "1300"
	CODE_NEW_CUSTOMER_SPOSE_BADTYPE_B                            = "7011"
	CODE_NEW_CUSTOMER_SPOSE_MAX_OVER_DUE_DAYS                    = "7012"
	CODE_NEW_CUSTOMER_SPOSE_NUM_OF_ASSET_INVENTORIED             = "7013"
	CODE_NEW_CUSTOMER_SPOSE_BADTYPE_W                            = "7014"
	CODE_NEW_CUSTOMER_SPOSE_BERSIH                               = "7015"
	CODE_NEW_CUSTOMER_SPOSE                                      = "7016"
	CODE_PASANGAN_BARU                                           = "7055"
	REASON_SPOSE_BADTYPE_B                                       = "Pasangan Blacklist - BadType B"
	REASON_SPOSE_MAX_OVER_DUE_DAYS                               = "Pasangan Blacklist - Max OVD > 90"
	REASON_SPOSE_NUM_OF_ASSET_INVENTORIED                        = "Pasangan Blacklist - NumOfAssetInventoried > 0"
	REASON_IS_RESTRUCTURE                                        = "Pasangan Blacklist - Restructure"
	REASON_SPOSE_BADTYPE_W                                       = "Pasangan Warning"
	REASON_SPOSE_BERSIH                                          = "Pasangan Bersih"
	REASON_IS_SIMILIAR_ID                                        = "Konsumen Blacklist - Similar ID"
	REASON_SPOSE_IS_RESTRUCTURE                                  = "Konsumen Blacklist - Konsumen Restructure"
	REASON_SPOSE_IS_RESTRUCTURE_BADTYPE_B                        = "Konsumen Restructure & Pasangan Blacklist - Badtype B"
	REASON_SPOSE_IS_RESTRUCTURE_MAX_OVER_DUE_DAYS                = "Konsumen Restructure & Pasangan Blacklist - Max OVD > 90"
	REASON_SPOSE_IS_RESTRUCTURE_NUM_OF_ASSET_INVENTORIED         = "Konsumen Restructure &  Pasangan Blacklist - NumOfAssetInventoried > 0"
	REASON_SPOSE_IS_RESTRUCTURE_BADTYPE_W                        = "Konsumen Restructure & Pasangan Warning"
	REASON_SPOSE_IS_RESTRUCTURE_BERSIH                           = "Konsumen Restructure & Pasangan Bersih"
	REASON_NEW_CUSTOMER_IS_RESTRUCTURE                           = "Konsumen Baru & Pasangan Restructure"
	REASON_NEW_CUSTOMER                                          = "Konsumen Baru"
	REASON_PASANGAN_BARU                                         = "Pasangan Baru"
	DECISION_REJECT                                              = "REJECT"
	DECISION_PASS                                                = "PASS"
	DECISION_APPROVE                                             = "APPROVE"
	DECISION_CANCEL                                              = "CANCEL"
	STATUS_KONSUMEN_RO_AO                                        = "RO/AO"
	STATUS_KONSUMEN_NEW                                          = "NEW"
	REASON_BADTYPE_B                                             = "Konsumen Blacklist - BadType B"
	REASON_MAX_OVER_DUE_DAYS                                     = "Konsumen Blacklist - Max OVD > 90"
	REASON_NUM_OF_ASSET_INVENTORIED                              = "Konsumen Blacklist - NumOfAssetInventoried > 0"
	REASON_BADTYPE_W                                             = "Konsumen Warning"
	REASON_BERSIH                                                = "Konsumen Bersih"
	REASON_SESUAI                                                = "Sesuai"
	REASON_TIDAK_SESUAI                                          = "Tidak Sesuai"
	CODE_NON_BLACKLIST                                           = "1300,7064,7065,7066,706,7094,7095,7096,708,7014,7015,7016,7053,7054,7055,699,7050"
	CODE_NON_BLACKLIST_ALL                                       = "609"
	CORE_API_003                                                 = "CORE-API-003"
	CORE_API_004                                                 = "CORE-API-004"
	CORE_API_099                                                 = "CORE-API-999"
	CORE_API_005                                                 = "CORE-API-005"
	CORE_API_019                                                 = "CORE-API-019"
	KREDITMU_VERIFY                                              = "VERIFY"
	KREDITMU_ACTIVE                                              = "ACTIVE"
	KREDITMU_INACTIVE                                            = "INACTIVE"
	KREDITMU_STATUS_CODE_RO_AO                                   = "8031"
	KREDITMU_STATUS_CODE_NEW                                     = "8032"
	KREDITMU_NEW                                                 = "800"
	REASON_KREDITMU_STATUS_CODE_RO_AO                            = "KREDITMU RO/AO"
	REASON_CUSTOMER_STATUS_CODE_RO_AO                            = "CUSTOMER RO/AO"
	REASON_CUSTOMER_STATUS_CODE_RO_AO_PRIME_PRIORITY             = "RO/AO PRIME PRIORITY"
	CUSTOMER_STATUS_CODE_RO_AO_PRIME_PRIORITY                    = "8042"
	CUSTOMER_STATUS_CODE_RO_AO                                   = "8041"
	CUSTOMER_STATUS_CODE_NEW                                     = "8040"
	CUSTOMER_NEW                                                 = "800"
	RO_AO_PRIME                                                  = "PRIME"
	RO_AO_PRIORITY                                               = "PRIORITY"
	RO_AO_REGULAR                                                = "REGULAR"
	REASON_CUSTOMER_STATUS_CODE_NEW                              = "CUSTOMER NEW"
	REASON_KREDITMU_STATUS_CODE_NEW                              = "KREDITMU NEW"
	NAMA_BEDA_CURRENT_OVD_NULL_CODE                              = "9098"
	NAMA_BEDA_CURRENT_OVD_UNDER_LIMIT_CODE                       = "9096"
	NAMA_BEDA_CURRENT_OVD_OVER_LIMIT_CODE                        = "9097"
	NAMA_BEDA_12_OVD_OVER_LIMIT_CODE                             = "9099"
	NAMA_BEDA_12_OVD_NULL_CODE                                   = "9095"
	NAMA_SAMA_CURRENT_OVD_NULL_CODE                              = "9102"
	NAMA_SAMA_CURRENT_OVD_UNDER_LIMIT_CODE                       = "9103"
	NAMA_SAMA_CURRENT_OVD_OVER_LIMIT_CODE                        = "9105"
	NAMA_SAMA_12_OVD_OVER_LIMIT_CODE                             = "9106"
	NAMA_SAMA_12_OVD_NULL_CODE                                   = "9104"
	NAMA_SAMA_WO_AGUNAN_PASS_CODE                                = "9101"
	NAMA_SAMA_WO_AGUNAN_REJECT_CODE                              = "9016"
	NAMA_SAMA_NO_FACILITY_WO_CODE                                = "9016"
	NAMA_SAMA_UNSCORE_RO_AO_CODE                                 = "9190"
	NAMA_SAMA_UNSCORE_NEW_CODE                                   = "9192"
	SERVICE_PBK_UNAVAILABLE_CODE                                 = "9194"
	PBK_NO_HIT                                                   = "9195"
	DECISION_PBK_NO_HIT                                          = "NO HIT"
	UNSCORE_PBK                                                  = "UNSCORE"
	NOT_MATCH_PBK                                                = "NOT_MATCH"
	WO_AGUNAN_REJECT_CODE                                        = "9107"
	WO_AGUNAN_PASS_CODE                                          = "9108"
	NAMA_SAMA_BAKI_DEBET_SESUAI                                  = "Nama Sama & Baki Debet Sesuai Ketentuan"
	NAMA_BEDA_BAKI_DEBET_SESUAI                                  = "Nama Beda & Baki Debet Sesuai Ketentuan"
	NAMA_SAMA_BAKI_DEBET_TIDAK_SESUAI                            = "Nama Sama & Baki Debet > 20 Juta"
	NAMA_BEDA_BAKI_DEBET_TIDAK_SESUAI                            = "Nama Beda & Baki Debet > 20 Juta"
	ADA_FASILITAS_WO_AGUNAN                                      = "Ada Fasilitas WO Agunan"
	TIDAK_ADA_FASILITAS_WO_AGUNAN                                = "Tidak Ada Fasilitas WO Agunan"
	REASON_FILTERING_PBK_DOWN                                    = "No Hit PBK"

	// Error Message
	INTERNAL_SERVER_ERROR     = "internal_server_error"
	ERROR_CONNECTION          = "connection error"
	ERROR_UNMARSHAL           = "unmarshal error"
	ERROR_UPSTREAM            = "upstream_service_error"
	ERROR_UPSTREAM_TIMEOUT    = "upstream_service_timeout"
	ERROR_BAD_REQUEST         = "bad_request"
	ERROR_SERVICE_UNAVAILABLE = "service_unavailable"
	ERROR_DATA_CONFLICT       = "data_conflict"
	ERROR_UNAUTHORIZED        = "unauthorized"
	ERROR_INACTIVE_CREDENTIAL = "inactive_credential"

	HEADER_CLIENT_ID     = "X-Client-ID"
	HEADER_AUTHORIZATION = "Authorization"

	// Key
	HeaderXRequestID                = "X-Request-ID"
	CTX_KEY_REQUEST_TIME            = "RequestTime"
	CTX_KEY_TAG_VERSION             = "TagVersion"
	CTX_KEY_LOS_VERSION             = "LOSVersion"
	CTX_KEY_INCOMING_REQUEST_URL    = "IncomingRequestURL"
	CTX_KEY_INCOMING_REQUEST_METHOD = "IncomingRequestMethod"
	CTX_KEY_IS_CONSUMER             = "IsKafkaConsumer"
	MSG_INCOMING_REQUEST            = "INCOMING_REQUEST"

	//Platform Log
	PLATFORM_LOG_LEVEL_INFO     = "INFO"
	PLATFORM_LOG_LEVEL_WARNING  = "WARNING"
	PLATFORM_LOG_LEVEL_ERROR    = "ERROR"
	PLATFORM_LOG_LEVEL_CRITICAL = "CRITICAL"
	LOG_EVENT                   = "LOG_EVENT"

	MSG_PUBLISH_DATA_STREAM = "PUBLISH_DATA_STREAM"
	MSG_CONSUME_DATA_STREAM = "CONSUME_DATA_STREAM"
	MSG_MEDIA_API           = "PLATFORM_MEDIA_API"

	//Platform Event
	KEY_PREFIX_FILTERING               = "filtering"
	KEY_PREFIX_UPDATE_STATUS_FILTERING = "update_status_filtering"
	KEY_PREFIX_SUBMIT_TO_LOS           = "submit_los_kmb"
	KEY_PREFIX_AFTER_PRESCREENING      = "after_prescreening_los_kmb"
	KEY_PREFIX_CALLBACK                = "callback_los_kmb"

	MAX_RETRY_PUBLISH = 3

	// Format
	FORMAT_DATE_TIME_MS = "2006/01/02 15:04:05.000"
	FORMAT_DATE         = "2006-01-02"
	FORMAT_DATE_TIME    = "2006-01-02 15:04:05"

	//LogFile
	FILTERING_LOG        = "FILTERING_LOG"
	DUPCHECK_LOG         = "DUPCHECK_LOG"
	LOG_FACE_COMPARE_TRX = "LOG_FACE_COMPARE_TRX"
	NEW_KMB_LOG          = "NEW_KMB_LOG"

	// ELABORATE SCHEME
	MESSAGE_KMB_ELABORATE           = "KMB-ELABORATE"
	CODE_PASS_ELABORATE             = 9601
	CODE_REJECT_ELABORATE           = 9602
	CODE_REJECT_NTF_ELABORATE       = 9603
	RANGE_CLUSTER_BAKI_DEBET_REJECT = 3000000
	REASON_PASS_ELABORATE           = "PASS - Elaborated Scheme"
	REASON_REJECT_ELABORATE         = "REJECT - Elaborated Scheme"
	REASON_REJECT_NTF_ELABORATE     = "REJECT - NTF Tidak Sesuai Threshold"
	CLUSTER_C                       = "Cluster C"
	CLUSTER_E                       = "Cluster E"
	CLUSTER_F                       = "Cluster F"
	BRANCH_ID_PRIME_PRIORITY        = "000"
	CLUSTER_PRIME_PRIORITY          = "PRIME PRIORITY"

	//HTTP MSG
	MSG_CORE_API          = "CORE_API"
	MSG_INT_API           = "INTEGRATOR_API"
	MSG_PLATFORM_API      = "PLATFORM_API"
	CORE_TOKEN_EXPIRED    = "CORE-AUTH-004"
	TOKEN_INVALID         = "token tidak valid."
	RESTY_MAX_RETRY_ERROR = "Max retry attempt exceeded"
	ERROR_NOT_FOUND       = "data_not_found"

	//PRE SCREENING
	LIMIT_PRESCREENING = 20000000

	//TENOR
	SOURCE_DECISION_TENOR = "TNR"

	//DUPCHECK
	SOURCE_DECISION_DUPCHECK                = "DCK"
	FLAG_ON                                 = "ON"
	AGREEMENT_AKTIF                         = "AKTIF"
	AGREEMENT_LUNAS                         = "LUNAS"
	STATUS_KONSUMEN_AO                      = "AO"
	STATUS_KONSUMEN_RO                      = "RO"
	CODE_MAX_OVD_CONFINS                    = "651"
	CODE_RO_OVDLTE30                        = "612"
	CODE_RO_OVDGT30_LTE90                   = "613"
	CODE_RO_OVDGT90                         = "614"
	CODE_AO_LANCAR_ANGSGT6_OVDLTE30         = "625"
	CODE_AO_LANCAR_ANGSGT6_OVDGT30_LTE90    = "626"
	CODE_AO_LANCAR_ANGSGT6_OVDGT90          = "627"
	CODE_AO_OVDGT90                         = "638"
	CODE_AO_LANCAR_ANGSLTE6_OVDLTE30        = "628"
	CODE_AO_LANCAR_ANGSLTE6_OVDGT30         = "629"
	CODE_AO_MENUNGGAK_ANGSGT6_OVDLTE30      = "633"
	CODE_AO_MENUNGGAK_ANGSGT6_OVDGT30_LTE90 = "634"
	CODE_AO_MENUNGGAK_ANGSGT6_OVDGT90       = "635"
	CODE_AO_MENUNGGAK_ANGSLTE6_OVDLTE30     = "636"
	CODE_AO_MENUNGGAK_ANGSLTE6_OVDGT30      = "637"
	CODE_KONSUMEN_UNIDENTIFIED              = "640"
	CODE_KONSUMEN_NEW                       = "600"
	REASON_REJECT_CONFINS_MAXOVD            = "- Confins Max Ovd >"
	REASON_KONSUMEN_UNIDENTIFIED            = "Konsumen Unidentified"
	REASON_KONSUMEN_NEW                     = "Konsumen NEW"

	// PERNAH REJECT
	CODE_PERNAH_REJECT_PMK_DSR            = "301"
	REASON_PERNAH_REJECT_PMK_DSR          = "Pernah Reject karena PMK atau DSR"
	CODE_PERNAH_REJECT_NIK                = "302"
	REASON_PERNAH_REJECT_NIK              = "Pernah Reject karena NIK KTP"
	CODE_BELUM_PERNAH_REJECT              = "303"
	REASON_BELUM_PERNAH_REJECT            = "Bersih"
	SOURCE_DECISION_NIK                   = "NIK"
	SOURCE_DECISION_PERNAH_REJECT_PMK_DSR = "PRJ"

	// BLACKLIST
	SOURCE_DECISION_BLACKLIST                 = "BLK"
	MESSAGE_BLACKLIST                         = "Blacklist"
	MESSAGE_WARNING                           = "Warning"
	MESSAGE_BERSIH                            = "Bersih"
	MESSAGE_SIMILIAR                          = "Similiar"
	CODE_KONSUMEN_SIMILIAR                    = "680"
	CODE_KONSUMEN_BLACKLIST                   = "607"
	CODE_PASANGAN_BLACKLIST                   = "608"
	REASON_KONSUMEN_SIMILIAR                  = "Konsumen SimiliarID = 1"
	REASON_KONSUMEN_BLACKLIST                 = "Konsumen Blacklist"
	REASON_PASANGAN_BLACKLIST                 = "Pasangan Blacklist"
	REASON_KONSUMEN_BLACKLIST_OVD_90DAYS      = "Konsumen Blacklist - Max Ovd > 90 Days"
	REASON_PASANGAN_BLACKLIST_OVD_90DAYS      = "Pasangan Blacklist - Max Ovd > 90 Days"
	REASON_KONSUMEN_BLACKLIST_ASSET_INVENTORY = "Konsumen Blacklist - Asset Inventory > 0"
	REASON_PASANGAN_BLACKLIST_ASSET_INVENTORY = "Pasangan Blacklist - Asset Inventory > 0"
	REASON_KONSUMEN_BLACKLIST_RESTRUCTURE     = "Konsumen Blacklist - Konsumen Restructure"
	REASON_PASANGAN_BLACKLIST_RESTRUCTURE     = "Pasangan Blacklist - Pasangan Restructure"
	REASON_NON_BLACKLIST                      = "Non Blacklist"

	//DSR
	SOURCE_DECISION_DSR    = "DSR"
	CODE_DSRLTE35          = "2701"
	CODE_DSRGT35           = "2702"
	REASON_DSRLTE          = "- DSR <="
	REASON_DSRGT           = "- DSR >"
	REASON_DSRLTE35        = "- Confins DSR <="
	REASON_DSRGT35         = "- Confins DSR >"
	CODE_TOPUP_MENUNGGAK   = "2703"
	REASON_TOPUP_MENUNGGAK = "- Top Up Menunggak"
	TOP_UP                 = "Top Up"

	DEALER_PSA     = "PSA"
	DEALER_NON_PSA = "NON PSA"

	//PMK
	SOURCE_DECISION_PMK             = "PMK"
	CODE_REJECT_WORK_EXPERIENCE     = "401"
	CODE_REJECT_INCOME              = "402"
	CODE_REJECT_MIN_AGE             = "403"
	CODE_REJECT_MAX_AGE             = "404"
	CODE_PMK_SESUAI                 = "406"
	CODE_REJECT_HOME_SINCE          = "413"
	CODE_VEHICLE_AGE_MAX            = "451"
	CODE_VEHICLE_SESUAI             = "452"
	REASON_PMK_SESUAI               = "Konsumen Bersih"
	REASON_REJECT_INCOME            = "Penghasilan Dibawah Minimum Ketentuan"
	REASON_REJECT_WORK_EXPERIENCE   = "Lama Usaha/Bekerja Tidak Sesuai PMK"
	REASON_REJECT_HOME_SINCE        = "Lama Tinggal Tidak Sesuai PMK"
	REASON_REJECT_MIN_AGE_THRESHOLD = "Minimal Umur < Threshold"
	REASON_REJECT_MAX_AGE           = "Umur Diatas Limit Ketentuan"
	REASON_VEHICLE_SESUAI           = "Umur Kendaraan Sesuai Ketentuan"
	REASON_VEHICLE_AGE_MAX          = "Usia Kendaraan >"
	DEFAULT_BRANCH_ID               = "DEFAULT"

	//NOKA NOSIN
	ATTEMPT_REJECT                   = 2
	ATTEMPT_REJECT_PMK_DSR           = 2
	ATTEMPT_BANNED_REJECTION_NOKA    = 3
	DAY_RANGE_BANNED_REJECT_NOKA     = 30
	DAY_RANGE_BLACKLIST_PMK          = 30
	TYPE_API_LOGS_NOKA               = "API_CHECK_NOKA"
	RESULT_NOTIF                     = "NOTIF"
	RESULT_OK                        = "OK"
	REASON_NOTIF                     = "Failed to check status agreement based on Chassis Number"
	RESULT_REJECTION_OK              = "Rejection Check OK, Next Process"
	REASON_REJECTION_OK              = "Skip Check Rejection NIK & DSR karena sudah reject NOKA"
	CODE_REJECT_NIK_KTP              = "651"
	CODE_REJECT_PMK_DSR              = "652"
	CODE_REJECT_CHASSIS_NUMBER       = "653"
	CODE_OK_CONSUMEN_MATCH           = "654"
	CODE_REJECT_NOKA_NOSIN           = "655"
	CODE_AGREEMENT_NOT_FOUND         = "656"
	CODE_REJECTION_NOTIF             = "666"
	CODE_REJECTION_FRAUD_POTENTIAL   = "667"
	CODE_REJECTION_OK                = "660"
	REASON_REJECT_PMK_DSR            = "Pernah Reject karena PMK atau DSR"
	REASON_REJECT_NIK_KTP            = "Pernah Reject karena NIK KTP"
	REASON_REJECT_NOKA_NOSIN         = "Reject NokaNosin"
	REASON_REJECT_CHASSIS_NUMBER     = "NokaNosin sudah terdaftar di KBFMF - Bukan a.n Konsumen dan Pasangan"
	REASON_OK_CONSUMEN_MATCH         = "NokaNosin sudah terdaftar di KBFMF - Agreement Aktif a.n Konsumen"
	REASON_REJECTION_FRAUD_POTENTIAL = "NokaNosin sudah terdaftar di KBFMF - Agreement Aktif a.n Pasangan"
	REASON_AGREEMENT_NOT_FOUND       = "NokaNosin tidak terdaftar di KBFMF"
	SOURCE_DECISION_NOKANOSIN        = "NKA"

	//FACE COMPARE
	RESULT_COMPARE                    = true
	CODE_REJECT_FACE_COMPARE          = "661"
	CANNOT_GET_IMAGE                  = "bypass get image error"
	GROUP_FPP                         = "face_plus"
	REASON_CONFIDENCE_BELOW_THRESHOLD = "Confidence Di Bawah Threshold"
	REASON_CONFIDENCE_UPPER_THRESHOLD = "Confidence Di Atas Threshold"

	//LOB
	LOB_NEW_KMB = "NEW-KMB"
	LOB_KMB     = "KMB"

	//LOG
	LOG_FILTERING_LOG = "FILTERING_LOG"

	// Flag Logging
	USECASE_API = "USECASE_API"

	//Reject Tenor
	CODE_PASS_TENOR     = "010"
	CODE_REJECT_TENOR   = "013"
	REASON_PASS_TENOR   = "Pass Tenor Pengajuan"
	REASON_REJECT_TENOR = "Tenor > Threshold"

	// EKYC
	SOURCE_DECISION_DUKCAPIL            = "DCP"
	REASON_DUKCAPIL_RTO                 = "Dukcapil RTO"
	REASON_DUKCAPIL_NOT_CHECK           = "Dukcapil Not Check"
	CODE_ERROR_DUKCAPIL_VD              = "1610"
	CODE_ERROR_DUKCAPIL_FR              = "1620"
	DUKCAPIL_VERIFICATION_DATA          = "DVN"
	DUKCAPIL_FACE_RECOGNITION           = "DFR"
	SOURCE_DECISION_ASLIRI              = "ARI"
	CODE_REJECT_ASLIRI_NOT_FOUND        = "1528"
	CODE_REJECT_ASLIRI_NAME             = "1527"
	CODE_REJECT_ASLIRI_SELFIE           = "1526"
	CODE_PASS_ASLIRI                    = "1525"
	REASON_ASLIRI_VALID                 = "Asliri Valid"
	REASON_ASLIRI_INVALID               = "Asliri Invalid"
	SOURCE_DECISION_KTP_VALIDATOR       = "KTP"
	TAG_SELFIE_PHOTO                    = "SELFIE"
	TAG_KTP_PHOTO                       = "KTP"
	REASON_EKYC_VALID                   = "Ekyc Valid"
	REASON_EKYC_INVALID                 = "Ekyc Invalid"
	ASLIRI                              = "ARI"
	KTP                                 = "KTP"
	CODE_VERIFICATION_PASS_EKYC         = "1611"
	CODE_VERIFICATION_REJECT_EKYC       = "1612"
	CODE_VERIFICATION_REJECT_MENINGGAL  = "1613"
	CODE_VERIFICATION_REJECT_DATA_GANDA = "1614"
	CODE_VERIFICATION_REJECT_INACTIVE   = "1615"
	CODE_VERIFICATION_REJECT_NOT_FOUND  = "1616"
	CODE_FACERECOGNITION_PASS           = "1621"
	CODE_FACERECOGNITION_REJECT_FOTO    = "1622"
	CODE_FACERECOGNITION_REJECT_NIK     = "1623"
	CUSTOMER_MENINGGAL                  = "Customer Meninggal Dunia"
	DATA_GANDA                          = "Data Ganda"
	DATA_INACTIVE                       = "Data Inactive"
	DATA_NOT_FOUND                      = "Data Not Found"
	EKYC_VALID                          = "Ekyc Valid"

	// Address Type
	ADDRESS_TYPE_LEGAL     = "LEGAL"
	ADDRESS_TYPE_RESIDENCE = "RESIDENCE"
	ADDRESS_TYPE_COMPANY   = "COMPANY"
	ADDRESS_TYPE_EMERGENCY = "EMERGENCY"
	ADDRESS_TYPE_LOCATION  = "LOCATION"
	ADDRESS_TYPE_MAILING   = "MAILING"

	// BIRO
	SOURCE_DECISION_BIRO = "BIR"

	// CREDIT ANALYST
	SOURCE_DECISION_CA    = "CRA"
	CODE_CREDIT_COMMITTEE = "2743"
	NEED_DECISION         = "need_decision"
	SAVED_AS_DRAFT        = "saved_as_draft"
	// PRE SCREENING
	CODE_PASS_PRESCREENING   = 9701
	CODE_REJECT_PRESCREENING = 9702
)
