// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "los-kmb-api/models/request"

	response "los-kmb-api/models/response"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// CheckStatusCategory provides a mock function with given fields: ctx, reqs, status_konsumen, accessToken
func (_m *Usecase) CheckStatusCategory(ctx context.Context, reqs request.FilteringRequest, status_konsumen string, accessToken string) (response.DupcheckResult, error) {
	ret := _m.Called(ctx, reqs, status_konsumen, accessToken)

	var r0 response.DupcheckResult
	if rf, ok := ret.Get(0).(func(context.Context, request.FilteringRequest, string, string) response.DupcheckResult); ok {
		r0 = rf(ctx, reqs, status_konsumen, accessToken)
	} else {
		r0 = ret.Get(0).(response.DupcheckResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.FilteringRequest, string, string) error); ok {
		r1 = rf(ctx, reqs, status_konsumen, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilteringBlackList provides a mock function with given fields: ctx, reqs, request_id
func (_m *Usecase) FilteringBlackList(ctx context.Context, reqs request.FilteringRequest, request_id string) (response.DupcheckResult, error) {
	ret := _m.Called(ctx, reqs, request_id)

	var r0 response.DupcheckResult
	if rf, ok := ret.Get(0).(func(context.Context, request.FilteringRequest, string) response.DupcheckResult); ok {
		r0 = rf(ctx, reqs, request_id)
	} else {
		r0 = ret.Get(0).(response.DupcheckResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.FilteringRequest, string) error); ok {
		r1 = rf(ctx, reqs, request_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilteringPefindo provides a mock function with given fields: ctx, reqs, status_konsumen, kategoriStatusKonsumen, request_id
func (_m *Usecase) FilteringPefindo(ctx context.Context, reqs request.FilteringRequest, status_konsumen string, kategoriStatusKonsumen string, request_id string) (response.DupcheckResult, error) {
	ret := _m.Called(ctx, reqs, status_konsumen, kategoriStatusKonsumen, request_id)

	var r0 response.DupcheckResult
	if rf, ok := ret.Get(0).(func(context.Context, request.FilteringRequest, string, string, string) response.DupcheckResult); ok {
		r0 = rf(ctx, reqs, status_konsumen, kategoriStatusKonsumen, request_id)
	} else {
		r0 = ret.Get(0).(response.DupcheckResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.FilteringRequest, string, string, string) error); ok {
		r1 = rf(ctx, reqs, status_konsumen, kategoriStatusKonsumen, request_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
