// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "los-kmb-api/models/request"

	response "los-kmb-api/models/response"
)

// MultiUsecase is an autogenerated mock type for the MultiUsecase type
type MultiUsecase struct {
	mock.Mock
}

// Elaborate provides a mock function with given fields: ctx, reqs, accessToken
func (_m *MultiUsecase) Elaborate(ctx context.Context, reqs request.BodyRequestElaborate, accessToken string) (response.ElaborateResult, error) {
	ret := _m.Called(ctx, reqs, accessToken)

	var r0 response.ElaborateResult
	if rf, ok := ret.Get(0).(func(context.Context, request.BodyRequestElaborate, string) response.ElaborateResult); ok {
		r0 = rf(ctx, reqs, accessToken)
	} else {
		r0 = ret.Get(0).(response.ElaborateResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.BodyRequestElaborate, string) error); ok {
		r1 = rf(ctx, reqs, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
