// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "los-kmb-api/models/entity"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetClusterBranchElaborate provides a mock function with given fields: branchId, customerStatus, bpkb
func (_m *Repository) GetClusterBranchElaborate(branchId string, customerStatus string, bpkb int) (entity.ClusterBranch, error) {
	ret := _m.Called(branchId, customerStatus, bpkb)

	var r0 entity.ClusterBranch
	if rf, ok := ret.Get(0).(func(string, string, int) entity.ClusterBranch); ok {
		r0 = rf(branchId, customerStatus, bpkb)
	} else {
		r0 = ret.Get(0).(entity.ClusterBranch)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int) error); ok {
		r1 = rf(branchId, customerStatus, bpkb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFilteringResult provides a mock function with given fields: prospect_id
func (_m *Repository) GetFilteringResult(prospect_id string) (entity.ApiDupcheckKmbUpdate, error) {
	ret := _m.Called(prospect_id)

	var r0 entity.ApiDupcheckKmbUpdate
	if rf, ok := ret.Get(0).(func(string) entity.ApiDupcheckKmbUpdate); ok {
		r0 = rf(prospect_id)
	} else {
		r0 = ret.Get(0).(entity.ApiDupcheckKmbUpdate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(prospect_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMappingLtvOvd provides a mock function with given fields: cluster, resultPefindo, tenor, ltv
func (_m *Repository) GetMappingLtvOvd(cluster string, resultPefindo string, tenor int, ltv float64) (entity.ResultElaborate, error) {
	ret := _m.Called(cluster, resultPefindo, tenor, ltv)

	var r0 entity.ResultElaborate
	if rf, ok := ret.Get(0).(func(string, string, int, float64) entity.ResultElaborate); ok {
		r0 = rf(cluster, resultPefindo, tenor, ltv)
	} else {
		r0 = ret.Get(0).(entity.ResultElaborate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int, float64) error); ok {
		r1 = rf(cluster, resultPefindo, tenor, ltv)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResultElaborate provides a mock function with given fields: branchId, customerStatus, bpkb, resultPefindo, tenor, ageVehicle, ltv, bakiDebet
func (_m *Repository) GetResultElaborate(branchId string, customerStatus string, bpkb int, resultPefindo string, tenor int, ageVehicle string, ltv float64, bakiDebet float64) (entity.ResultElaborate, error) {
	ret := _m.Called(branchId, customerStatus, bpkb, resultPefindo, tenor, ageVehicle, ltv, bakiDebet)

	var r0 entity.ResultElaborate
	if rf, ok := ret.Get(0).(func(string, string, int, string, int, string, float64, float64) entity.ResultElaborate); ok {
		r0 = rf(branchId, customerStatus, bpkb, resultPefindo, tenor, ageVehicle, ltv, bakiDebet)
	} else {
		r0 = ret.Get(0).(entity.ResultElaborate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int, string, int, string, float64, float64) error); ok {
		r1 = rf(branchId, customerStatus, bpkb, resultPefindo, tenor, ageVehicle, ltv, bakiDebet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveDataElaborate provides a mock function with given fields: data
func (_m *Repository) SaveDataElaborate(data entity.ApiElaborateKmb) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.ApiElaborateKmb) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDataElaborate provides a mock function with given fields: data
func (_m *Repository) UpdateDataElaborate(data entity.ApiElaborateKmbUpdate) error {
	ret := _m.Called(data)

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.ApiElaborateKmbUpdate) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
