// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "los-kmb-api/models/entity"

	mock "github.com/stretchr/testify/mock"

	request "los-kmb-api/models/request"

	response "los-kmb-api/models/response"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// ApprovalScheme provides a mock function with given fields: req
func (_m *Usecase) ApprovalScheme(req request.ReqSubmitApproval) (response.RespApprovalScheme, error) {
	ret := _m.Called(req)

	var r0 response.RespApprovalScheme
	if rf, ok := ret.Get(0).(func(request.ReqSubmitApproval) response.RespApprovalScheme); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(response.RespApprovalScheme)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(request.ReqSubmitApproval) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CancelOrder provides a mock function with given fields: ctx, req
func (_m *Usecase) CancelOrder(ctx context.Context, req request.ReqCancelOrder) (response.CancelResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 response.CancelResponse
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqCancelOrder) response.CancelResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.CancelResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqCancelOrder) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetApprovalReason provides a mock function with given fields: ctx, req, pagination
func (_m *Usecase) GetApprovalReason(ctx context.Context, req request.ReqApprovalReason, pagination interface{}) ([]entity.ApprovalReason, int, error) {
	ret := _m.Called(ctx, req, pagination)

	var r0 []entity.ApprovalReason
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqApprovalReason, interface{}) []entity.ApprovalReason); ok {
		r0 = rf(ctx, req, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ApprovalReason)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqApprovalReason, interface{}) int); ok {
		r1 = rf(ctx, req, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, request.ReqApprovalReason, interface{}) error); ok {
		r2 = rf(ctx, req, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCancelReason provides a mock function with given fields: ctx, pagination
func (_m *Usecase) GetCancelReason(ctx context.Context, pagination interface{}) ([]entity.CancelReason, int, error) {
	ret := _m.Called(ctx, pagination)

	var r0 []entity.CancelReason
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) []entity.CancelReason); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CancelReason)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, interface{}) int); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, interface{}) error); ok {
		r2 = rf(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetInquiryApproval provides a mock function with given fields: ctx, req, pagination
func (_m *Usecase) GetInquiryApproval(ctx context.Context, req request.ReqInquiryApproval, pagination interface{}) ([]entity.InquiryDataApproval, int, error) {
	ret := _m.Called(ctx, req, pagination)

	var r0 []entity.InquiryDataApproval
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqInquiryApproval, interface{}) []entity.InquiryDataApproval); ok {
		r0 = rf(ctx, req, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InquiryDataApproval)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqInquiryApproval, interface{}) int); ok {
		r1 = rf(ctx, req, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, request.ReqInquiryApproval, interface{}) error); ok {
		r2 = rf(ctx, req, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetInquiryCa provides a mock function with given fields: ctx, req, pagination
func (_m *Usecase) GetInquiryCa(ctx context.Context, req request.ReqInquiryCa, pagination interface{}) ([]entity.InquiryDataCa, int, error) {
	ret := _m.Called(ctx, req, pagination)

	var r0 []entity.InquiryDataCa
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqInquiryCa, interface{}) []entity.InquiryDataCa); ok {
		r0 = rf(ctx, req, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InquiryDataCa)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqInquiryCa, interface{}) int); ok {
		r1 = rf(ctx, req, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, request.ReqInquiryCa, interface{}) error); ok {
		r2 = rf(ctx, req, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetInquiryPrescreening provides a mock function with given fields: ctx, req, pagination
func (_m *Usecase) GetInquiryPrescreening(ctx context.Context, req request.ReqInquiryPrescreening, pagination interface{}) ([]entity.InquiryData, int, error) {
	ret := _m.Called(ctx, req, pagination)

	var r0 []entity.InquiryData
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqInquiryPrescreening, interface{}) []entity.InquiryData); ok {
		r0 = rf(ctx, req, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InquiryData)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqInquiryPrescreening, interface{}) int); ok {
		r1 = rf(ctx, req, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, request.ReqInquiryPrescreening, interface{}) error); ok {
		r2 = rf(ctx, req, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetReasonPrescreening provides a mock function with given fields: ctx, req, pagination
func (_m *Usecase) GetReasonPrescreening(ctx context.Context, req request.ReqReasonPrescreening, pagination interface{}) ([]entity.ReasonMessage, int, error) {
	ret := _m.Called(ctx, req, pagination)

	var r0 []entity.ReasonMessage
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqReasonPrescreening, interface{}) []entity.ReasonMessage); ok {
		r0 = rf(ctx, req, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ReasonMessage)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqReasonPrescreening, interface{}) int); ok {
		r1 = rf(ctx, req, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, request.ReqReasonPrescreening, interface{}) error); ok {
		r2 = rf(ctx, req, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSearchInquiry provides a mock function with given fields: ctx, req, pagination
func (_m *Usecase) GetSearchInquiry(ctx context.Context, req request.ReqSearchInquiry, pagination interface{}) ([]entity.InquiryDataSearch, int, error) {
	ret := _m.Called(ctx, req, pagination)

	var r0 []entity.InquiryDataSearch
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqSearchInquiry, interface{}) []entity.InquiryDataSearch); ok {
		r0 = rf(ctx, req, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.InquiryDataSearch)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqSearchInquiry, interface{}) int); ok {
		r1 = rf(ctx, req, pagination)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, request.ReqSearchInquiry, interface{}) error); ok {
		r2 = rf(ctx, req, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ReturnOrder provides a mock function with given fields: ctx, req
func (_m *Usecase) ReturnOrder(ctx context.Context, req request.ReqReturnOrder) (response.ReturnResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 response.ReturnResponse
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqReturnOrder) response.ReturnResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.ReturnResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqReturnOrder) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReviewPrescreening provides a mock function with given fields: ctx, req
func (_m *Usecase) ReviewPrescreening(ctx context.Context, req request.ReqReviewPrescreening) (response.ReviewPrescreening, error) {
	ret := _m.Called(ctx, req)

	var r0 response.ReviewPrescreening
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqReviewPrescreening) response.ReviewPrescreening); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.ReviewPrescreening)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqReviewPrescreening) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveAsDraft provides a mock function with given fields: ctx, req
func (_m *Usecase) SaveAsDraft(ctx context.Context, req request.ReqSaveAsDraft) (response.CAResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 response.CAResponse
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqSaveAsDraft) response.CAResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.CAResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqSaveAsDraft) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitApproval provides a mock function with given fields: ctx, req
func (_m *Usecase) SubmitApproval(ctx context.Context, req request.ReqSubmitApproval) (response.ApprovalResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 response.ApprovalResponse
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqSubmitApproval) response.ApprovalResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.ApprovalResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqSubmitApproval) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitDecision provides a mock function with given fields: ctx, req
func (_m *Usecase) SubmitDecision(ctx context.Context, req request.ReqSubmitDecision) (response.CAResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 response.CAResponse
	if rf, ok := ret.Get(0).(func(context.Context, request.ReqSubmitDecision) response.CAResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(response.CAResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.ReqSubmitDecision) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
