// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Kredit Plus",
            "url": "https://kreditplus.com",
            "email": "support@kreditplus.com"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/elaborate": {
            "post": {
                "description": "KmbElaborate",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tools"
                ],
                "parameters": [
                    {
                        "description": "Body payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.BodyRequestElaborate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.ElaborateResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/response.ErrorValidation"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse"
                        }
                    }
                }
            }
        },
        "/filtering": {
            "post": {
                "description": "KmbFiltering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tools"
                ],
                "parameters": [
                    {
                        "description": "Body payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FilteringRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/response.DupcheckResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.ApiResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "$ref": "#/definitions/response.ErrorValidation"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request.BodyRequestElaborate": {
            "type": "object",
            "required": [
                "client_key",
                "data"
            ],
            "properties": {
                "client_key": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/request.DataElaborate"
                }
            }
        },
        "request.Data": {
            "type": "object",
            "required": [
                "BPKBName",
                "BirthDate",
                "BirthPlace",
                "BranchID",
                "Gender",
                "IDNumber",
                "LegalName",
                "MaritalStatus",
                "MobilePhone",
                "ProfessionID",
                "ProspectID",
                "SurgateMotherName"
            ],
            "properties": {
                "BPKBName": {
                    "type": "string"
                },
                "BirthDate": {
                    "type": "string"
                },
                "BirthPlace": {
                    "type": "string"
                },
                "BranchID": {
                    "type": "string"
                },
                "Gender": {
                    "type": "string"
                },
                "IDNumber": {
                    "type": "string"
                },
                "LegalName": {
                    "type": "string"
                },
                "MaritalStatus": {
                    "type": "string"
                },
                "MobilePhone": {
                    "type": "string"
                },
                "ProfessionID": {
                    "type": "string"
                },
                "ProspectID": {
                    "type": "string"
                },
                "Spouse": {
                    "type": "object",
                    "$ref": "#/definitions/request.Spouse"
                },
                "SurgateMotherName": {
                    "type": "string"
                }
            }
        },
        "request.DataElaborate": {
            "type": "object",
            "required": [
                "BPKBName",
                "BranchID",
                "CustomerStatus",
                "ManufacturingYear",
                "NTF",
                "OTR",
                "ProspectID",
                "ResultPefindo",
                "Tenor"
            ],
            "properties": {
                "BPKBName": {
                    "type": "string"
                },
                "BranchID": {
                    "type": "string"
                },
                "CategoryCustomer": {
                    "type": "string"
                },
                "CustomerStatus": {
                    "type": "string"
                },
                "ManufacturingYear": {
                    "type": "string"
                },
                "NTF": {
                    "type": "number"
                },
                "OTR": {
                    "type": "number"
                },
                "ProspectID": {
                    "type": "string"
                },
                "ResultPefindo": {
                    "type": "string"
                },
                "Tenor": {
                    "type": "integer"
                },
                "TotalBakiDebet": {
                    "type": "number"
                }
            }
        },
        "request.FilteringRequest": {
            "type": "object",
            "required": [
                "client_key",
                "data"
            ],
            "properties": {
                "client_key": {
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/request.Data"
                }
            }
        },
        "request.Spouse": {
            "type": "object",
            "required": [
                "Spouse_BirthDate",
                "Spouse_BirthPlace",
                "Spouse_Gender",
                "Spouse_IDNumber",
                "Spouse_LegalName",
                "Spouse_SurgateMotherName"
            ],
            "properties": {
                "Spouse_BirthDate": {
                    "type": "string"
                },
                "Spouse_BirthPlace": {
                    "type": "string"
                },
                "Spouse_Gender": {
                    "type": "string"
                },
                "Spouse_IDNumber": {
                    "type": "string"
                },
                "Spouse_LegalName": {
                    "type": "string"
                },
                "Spouse_SurgateMotherName": {
                    "type": "string"
                }
            }
        },
        "response.ApiResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "errors": {
                    "type": "object"
                },
                "messages": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "server_time": {
                    "type": "string"
                }
            }
        },
        "response.DupcheckResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "decision": {
                    "type": "string"
                },
                "is_blacklist": {
                    "type": "integer"
                },
                "kategori_status_konsumen": {
                    "type": "string"
                },
                "next_process": {
                    "type": "integer"
                },
                "pbk_report": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status_konsumen": {
                    "type": "string"
                },
                "total_baki_debet": {
                    "type": "number"
                }
            }
        },
        "response.ElaborateResult": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "decision": {
                    "type": "string"
                },
                "ltv": {
                    "type": "integer"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "response.ErrorValidation": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "localhost:9710",
	BasePath:    "/api/v2/pbk",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
