basePath: /api/v2/pbk
definitions:
  http.RequestEncryption:
    properties:
      decrypt:
        example:
        - 6gs+t7lBQTYM5SPuqJTNonWLjvmmmc9FaWIj
        items:
          type: string
        type: array
      encrypt:
        example:
        - hello world
        items:
          type: string
        type: array
    type: object
  request.BodyRequestElaborate:
    properties:
      client_key:
        type: string
      data:
        $ref: '#/definitions/request.DataElaborate'
    required:
    - client_key
    - data
    type: object
  request.Data:
    properties:
      BPKBName:
        type: string
      BirthDate:
        type: string
      BirthPlace:
        type: string
      BranchID:
        type: string
      Gender:
        type: string
      IDNumber:
        type: string
      LegalName:
        type: string
      MaritalStatus:
        type: string
      MobilePhone:
        type: string
      ProfessionID:
        type: string
      ProspectID:
        type: string
      Spouse:
        $ref: '#/definitions/request.Spouse'
      SurgateMotherName:
        type: string
    required:
    - BPKBName
    - BirthDate
    - BirthPlace
    - BranchID
    - Gender
    - IDNumber
    - LegalName
    - MaritalStatus
    - MobilePhone
    - ProfessionID
    - ProspectID
    - SurgateMotherName
    type: object
  request.DataElaborate:
    properties:
      BPKBName:
        type: string
      BranchID:
        type: string
      CategoryCustomer:
        type: string
      CustomerStatus:
        type: string
      ManufacturingYear:
        type: string
      NTF:
        type: number
      OTR:
        type: number
      ProspectID:
        type: string
      ResultPefindo:
        type: string
      Tenor:
        type: integer
      TotalBakiDebet:
        type: object
    required:
    - BPKBName
    - BranchID
    - CustomerStatus
    - ManufacturingYear
    - NTF
    - OTR
    - ProspectID
    - ResultPefindo
    - Tenor
    type: object
  request.DupcheckApi:
    properties:
      birth_date:
        type: string
      birth_place:
        type: string
      bpkb_name:
        type: string
      company_zip_code:
        type: string
      employment_since_month:
        type: string
      employment_since_year:
        type: string
      gender:
        type: string
      home_status:
        type: string
      id_number:
        type: string
      image_selfie:
        type: string
      installment_amount:
        type: number
      job_position:
        type: string
      ktp_url:
        type: string
      legal_name:
        type: string
      legal_zip_code:
        type: string
      manufacture_year:
        type: string
      marital_status:
        type: string
      monthly_fixed_income:
        type: number
      monthly_variable_income:
        type: number
      no_engine:
        type: string
      no_rangka:
        type: string
      ntf:
        type: number
      num_of_dependence:
        type: integer
      otr:
        type: number
      profession_id:
        type: string
      prospect_id:
        type: string
      spouse:
        $ref: '#/definitions/request.DupcheckApiSpouse'
      spouse_income:
        type: number
      stay_since_month:
        type: string
      stay_since_year:
        type: string
      surgate_mother_name:
        type: string
      tenor:
        type: integer
    required:
    - birth_date
    - birth_place
    - bpkb_name
    - company_zip_code
    - employment_since_month
    - employment_since_year
    - gender
    - home_status
    - id_number
    - image_selfie
    - installment_amount
    - job_position
    - ktp_url
    - legal_name
    - legal_zip_code
    - manufacture_year
    - monthly_fixed_income
    - no_engine
    - no_rangka
    - ntf
    - num_of_dependence
    - otr
    - profession_id
    - prospect_id
    - stay_since_month
    - stay_since_year
    - surgate_mother_name
    - tenor
    type: object
  request.DupcheckApiSpouse:
    properties:
      spouse_birth_date:
        type: string
      spouse_gender:
        type: string
      spouse_id_number:
        type: string
      spouse_legal_name:
        type: string
      spouse_surgate_mother_name:
        type: string
    required:
    - spouse_birth_date
    - spouse_gender
    - spouse_id_number
    - spouse_legal_name
    - spouse_surgate_mother_name
    type: object
  request.Filtering:
    properties:
      birth_date:
        example: YYYY-MM-DD
        type: string
      bpkb_name:
        example: K
        type: string
      branch_id:
        example: "426"
        type: string
      gender:
        example: M
        type: string
      id_number:
        example: ENCRYPTED NIK
        type: string
      legal_name:
        example: ENCRYPTED LEGAL NAME
        type: string
      prospect_id:
        example: SAL042600001
        type: string
      spouse:
        $ref: '#/definitions/request.FilteringSpouse'
      surgate_mother_name:
        example: ENCRYPTED SURGATE MOTHER NAME
        type: string
    required:
    - birth_date
    - bpkb_name
    - branch_id
    - gender
    - id_number
    - legal_name
    - prospect_id
    - surgate_mother_name
    type: object
  request.FilteringRequest:
    properties:
      client_key:
        type: string
      data:
        $ref: '#/definitions/request.Data'
    required:
    - client_key
    - data
    type: object
  request.FilteringSpouse:
    properties:
      spouse_birth_date:
        example: YYYY-MM-DD
        type: string
      spouse_gender:
        example: F
        type: string
      spouse_id_number:
        example: ENCRYPTED NIK
        type: string
      spouse_legal_name:
        example: ENCRYPTED LEGAL NAME
        type: string
      spouse_surgate_mother_name:
        example: ENCRYPTED SURGATE MOTHER NAME
        type: string
    required:
    - spouse_birth_date
    - spouse_gender
    - spouse_id_number
    - spouse_legal_name
    - spouse_surgate_mother_name
    type: object
  request.ReqRejectTenor:
    properties:
      id_number:
        example: 1234XXXXXXXX0001
        type: string
      prospect_id:
        type: string
    required:
    - id_number
    - prospect_id
    type: object
  request.Spouse:
    properties:
      Spouse_BirthDate:
        type: string
      Spouse_BirthPlace:
        type: string
      Spouse_Gender:
        type: string
      Spouse_IDNumber:
        type: string
      Spouse_LegalName:
        type: string
      Spouse_SurgateMotherName:
        type: string
    required:
    - Spouse_BirthDate
    - Spouse_BirthPlace
    - Spouse_Gender
    - Spouse_IDNumber
    - Spouse_LegalName
    - Spouse_SurgateMotherName
    type: object
  response.ApiResponse:
    properties:
      data:
        type: object
      errors:
        type: object
      messages:
        type: string
      request_id:
        type: string
      server_time:
        type: string
    type: object
  response.DupcheckResult:
    properties:
      code:
        type: object
      decision:
        type: string
      is_blacklist:
        type: integer
      kategori_status_konsumen:
        type: string
      next_process:
        type: integer
      pbk_report:
        type: string
      reason:
        type: string
      status_konsumen:
        type: string
      total_baki_debet:
        type: number
    type: object
  response.ElaborateResult:
    properties:
      age_vehicle:
        type: string
      bpkb_name_type:
        type: integer
      cluster:
        type: string
      code:
        type: integer
      decision:
        type: string
      ltv:
        type: integer
      ltv_origin:
        type: number
      reason:
        type: string
      result_pefindo:
        type: string
      total_balki_debet:
        type: number
    type: object
  response.ErrorValidation:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  response.Filtering:
    properties:
      code:
        type: object
      customer_segment:
        type: object
      customer_status:
        type: object
      decision:
        type: string
      is_blacklist:
        type: boolean
      next_process:
        type: boolean
      pbk_report_customer:
        type: object
      pbk_report_spouse:
        type: object
      prospect_id:
        type: string
      reason:
        type: string
      total_baki_debet:
        type: object
    type: object
  response.UsecaseApi:
    properties:
      code:
        type: string
      confidence:
        type: string
      dsr:
        type: number
      reason:
        type: string
      result:
        type: string
      status_konsumen:
        type: string
    type: object
host: localhost:9710
info:
  contact:
    email: support@kreditplus.com
    name: Kredit Plus
    url: https://kreditplus.com
paths:
  /api/v2/kmb/elaborate:
    post:
      description: KmbElaborate
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.BodyRequestElaborate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElaborateResult'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
  /api/v2/kmb/filtering:
    post:
      description: KmbFiltering
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.FilteringRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.DupcheckResult'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
  /api/v3/kmb/dupcheck:
    post:
      description: KmbDupcheck
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.DupcheckApi'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.DupcheckResult'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
  /api/v3/kmb/encrypt-decrypt:
    post:
      description: Encrypt Decrypt
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/http.RequestEncryption'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                data:
                  additionalProperties:
                    type: string
                  type: object
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
  /api/v3/kmb/filtering:
    post:
      description: KmbFiltering
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.Filtering'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.Filtering'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
  /api/v3/kmb/produce/filtering:
    post:
      description: Produce Filtering via REST API
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.Filtering'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ApiResponse'
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
  /api/v3/kmb/reject-tenor:
    post:
      description: KmbDupcheck
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.ReqRejectTenor'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.UsecaseApi'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
swagger: "2.0"
