basePath: /api/v2/pbk
definitions:
  request.BodyRequestElaborate:
    properties:
      client_key:
        type: string
      data:
        $ref: '#/definitions/request.DataElaborate'
        type: object
    required:
    - client_key
    - data
    type: object
  request.Data:
    properties:
      BPKBName:
        type: string
      BirthDate:
        type: string
      BirthPlace:
        type: string
      BranchID:
        type: string
      Gender:
        type: string
      IDNumber:
        type: string
      LegalName:
        type: string
      MaritalStatus:
        type: string
      MobilePhone:
        type: string
      ProfessionID:
        type: string
      ProspectID:
        type: string
      Spouse:
        $ref: '#/definitions/request.Spouse'
        type: object
      SurgateMotherName:
        type: string
    required:
    - BPKBName
    - BirthDate
    - BirthPlace
    - BranchID
    - Gender
    - IDNumber
    - LegalName
    - MaritalStatus
    - MobilePhone
    - ProfessionID
    - ProspectID
    - SurgateMotherName
    type: object
  request.DataElaborate:
    properties:
      BPKBName:
        type: string
      BranchID:
        type: string
      CategoryCustomer:
        type: string
      CustomerStatus:
        type: string
      ManufacturingYear:
        type: string
      NTF:
        type: number
      OTR:
        type: number
      ProspectID:
        type: string
      ResultPefindo:
        type: string
      Tenor:
        type: integer
      TotalBakiDebet:
        type: number
    required:
    - BPKBName
    - BranchID
    - CustomerStatus
    - ManufacturingYear
    - NTF
    - OTR
    - ProspectID
    - ResultPefindo
    - Tenor
    type: object
  request.FilteringRequest:
    properties:
      client_key:
        type: string
      data:
        $ref: '#/definitions/request.Data'
        type: object
    required:
    - client_key
    - data
    type: object
  request.Spouse:
    properties:
      Spouse_BirthDate:
        type: string
      Spouse_BirthPlace:
        type: string
      Spouse_Gender:
        type: string
      Spouse_IDNumber:
        type: string
      Spouse_LegalName:
        type: string
      Spouse_SurgateMotherName:
        type: string
    required:
    - Spouse_BirthDate
    - Spouse_BirthPlace
    - Spouse_Gender
    - Spouse_IDNumber
    - Spouse_LegalName
    - Spouse_SurgateMotherName
    type: object
  response.ApiResponse:
    properties:
      data:
        type: object
      errors:
        type: object
      messages:
        type: string
      request_id:
        type: string
      server_time:
        type: string
    type: object
  response.DupcheckResult:
    properties:
      code:
        type: string
      decision:
        type: string
      is_blacklist:
        type: integer
      kategori_status_konsumen:
        type: string
      next_process:
        type: integer
      pbk_report:
        type: string
      reason:
        type: string
      status_konsumen:
        type: string
      total_baki_debet:
        type: number
    type: object
  response.ElaborateResult:
    properties:
      code:
        type: integer
      decision:
        type: string
      ltv:
        type: integer
      reason:
        type: string
    type: object
  response.ErrorValidation:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
host: localhost:9710
info:
  contact:
    email: support@kreditplus.com
    name: Kredit Plus
    url: https://kreditplus.com
  license: {}
paths:
  /elaborate:
    post:
      description: KmbElaborate
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.BodyRequestElaborate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.ElaborateResult'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
  /filtering:
    post:
      description: KmbFiltering
      parameters:
      - description: Body payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.FilteringRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                data:
                  $ref: '#/definitions/response.DupcheckResult'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/response.ApiResponse'
            - properties:
                error:
                  $ref: '#/definitions/response.ErrorValidation'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ApiResponse'
      tags:
      - Tools
swagger: "2.0"
