// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "los-kmb-api/models/request"
)

// Metrics is an autogenerated mock type for the Metrics type
type Metrics struct {
	mock.Mock
}

// MetricsLos provides a mock function with given fields: ctx, req, accessToken
func (_m *Metrics) MetricsLos(ctx context.Context, req request.Metrics, accessToken string) (interface{}, error) {
	ret := _m.Called(ctx, req, accessToken)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(context.Context, request.Metrics, string) interface{}); ok {
		r0 = rf(ctx, req, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, request.Metrics, string) error); ok {
		r1 = rf(ctx, req, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
